const players = {
  br: {
    name: "Babe Ruth",
    image: "../img/br.jpg",
    position: "Right Fielder",
    wins: "7",
    selections: "2",
    bs1: "714 Home Runs",
    bs2: "2,214 RBIs",
    bs3: "1.164 OPS",
    hometown: "Baltimore, MD",
    nickname: "The Bambino",
  },
  lg: {
    name: "Lou Gehrig",
    image: "../img/lg.jpg",
    position: "First Baseman",
    wins: "6",
    selections: "7",
    bs1: "493 Home Runs",
    bs2: "1,995 RBIs",
    bs3: ".340 Batting Average",
    hometown: "New York, NY",
    nickname: "The Iron Horse",
  },
  mm: {
    name: "Mickey Mantle",
    image: "../img/mm.jpg",
    position: "Center Fielder",
    wins: "7",
    selections: "16",
    bs1: "536 Home Runs",
    bs2: "1,509 RBIs",
    bs3: "3x MVP",
    hometown: "Spavinaw, OK",
    nickname: "The Mick",
  },
  jd: {
    name: "Joe DiMaggio",
    image: "../img/jd.jpg",
    position: "Center Fielder",
    wins: "9",
    selections: "13",
    bs1: "361 Home Runs",
    bs2: "56-Game Hitting Streak",
    bs3: "3x MVP",
    hometown: "Martinez, CA",
    nickname: "Joltin' Joe",
  },
  yb: {
    name: "Yogi Berra",
    image: "../img/yb.jpg",
    position: "Catcher",
    wins: "10",
    selections: "18",
    bs1: "358 Home Runs",
    bs2: "1,430 RBIs",
    bs3: "3x MVP",
    hometown: "St. Louis, MO",
    nickname: "Yogi",
  },
  dj: {
    name: "Derek Jeter",
    image: "../img/dj.jpg",
    position: "Shortstop",
    wins: "5",
    selections: "14",
    bs1: "3,465 Hits",
    bs2: "5x World Series Champion",
    bs3: "5x Gold Glove",
    hometown: "Pequannock, NJ",
    nickname: "The Captain",
  },
  mr: {
    name: "Mariano Rivera",
    image: "../img/mr.jpg",
    position: "Closer",
    wins: "5",
    selections: "13",
    bs1: "652 Saves",
    bs2: "2.21 ERA",
    bs3: "5x World Series Champion",
    hometown: "Panama City, Panama",
    nickname: "Mo",
  },
  wf: {
    name: "Whitey Ford",
    image: "../img/wf.jpg",
    position: "Starting Pitcher",
    wins: "6",
    selections: "10",
    bs1: "236 Wins",
    bs2: "2.75 ERA",
    bs3: "8x World Series Champion",
    hometown: "New York, NY",
    nickname: "The Chairman of the Board",
  },
  tm: {
    name: "Thurman Munson",
    image: "../img/tm.jpg",
    position: "Catcher",
    wins: "3",
    selections: "7",
    bs1: "1,558 Hits",
    bs2: ".292 Batting Average",
    bs3: "3x Gold Glove",
    hometown: "Akron, OH",
    nickname: "The Wall",
  },
  bw: {
    name: "Bernie Williams",
    image: "../img/bw.jpg",
    position: "Center Fielder",
    wins: "4",
    selections: "5",
    bs1: "287 Home Runs",
    bs2: "1,257 RBIs",
    bs3: "4x World Series Champion",
    hometown: "San Juan, Puerto Rico",
    nickname: "Bernie",
  },
  aj: {
    name: "Aaron Judge",
    image: "../img/aj.jpg",
    position: "Right Fielder",
    wins: "1",
    selections: "6",
    bs1: "62 Home Runs (2017)",
    bs2: "2x MVP",
    bs3: "10x All-Star",
    hometown: "Linden, CA",
    nickname: "The Judge",
  },
  ar: {
    name: "Alex Rodriguez",
    image: "../img/ar.jpg",
    position: "Shortstop/Third Base",
    wins: "1",
    selections: "14",
    bs1: "696 Home Runs",
    bs2: "2,086 RBIs",
    bs3: "3x MVP",
    hometown: "New York, NY",
    nickname: "A-Rod",
  },
  dm: {
    name: "Don Mattingly",
    image: "../img/dm.jpg",
    position: "First Baseman",
    wins: "1",
    selections: "6",
    bs1: "2,153 Hits",
    bs2: ".307 Batting Average",
    bs3: "9x Gold Glove",
    hometown: "Evansville, IN",
    nickname: "Donnie Baseball",
  },
  ap: {
    name: "Andy Pettitte",
    image: "../img/ap.jpg",
    position: "Starting Pitcher",
    wins: "5",
    selections: "3",
    bs1: "256 Wins",
    bs2: "3.85 ERA",
    bs3: "5x World Series Champion",
    hometown: "Baton Rouge, LA",
    nickname: "Andy",
  },
  rj: {
    name: "Reggie Jackson",
    image: "../img/rj.jpg",
    position: "Right Fielder",
    wins: "2",
    selections: "14",
    bs1: "563 Home Runs",
    bs2: "1,702 RBIs",
    bs3: "5x World Series Champion",
    hometown: "Abington, PA",
    nickname: "Mr. October",
  },

  bd: {
    name: "Bill Dickey ",
    image: "../img/bd.jpg",
    position: "Catcher ",
    wins: "7",
    selections: "11",
    bs1: "National Baseball Hall of Fame Inductee",
    bs2: "Historical Single-Season Batting Record",
    bs3: "His number is retired to honor both him and Yogi Berra",
    hometown: "Bastrop, Louisiana",
    nickname: "The Man Nobody Knows",
  },
};